export default {
    LOGIN: "LOGIN",
    AUTH_LOGIN: "AUTH_LOGIN",
    AUTH_LOGOUT: "AUTH_LOGOUT",
    UPDATE_LOGIN_USER_ID: "UPDATE_LOGIN_USER_ID",
    UPDATE_LOGIN_USER_PWD: "UPDATE_LOGIN_USER_PWD",
    UPDATE_LOGOUT_USER_ID: "UPDATE_LOGOUT_USER_ID",
    UPDATE_LOGOUT_USER_PWD: "UPDATE_LOGOUT_USER_PWD",


    FETCH_POSTS: "FETCH_POSTS",
    SET_POSTS: "SET_POSTS",

}
